### ISSUE TITLE
Fails in Broccoli immediately

### ISSUE THREAD

**Issue by thedig** [mike-north/ember-rx-shim#1]
Have a very simple app with a single component. Looking to use this to make RxJs available. If I have this addon installed then `ember serve` fails immediately:

```
BroccoliMergeTrees: Expected Broccoli node, got undefined for inputNodes[0]
TypeError: BroccoliMergeTrees: Expected Broccoli node, got undefined for inputNodes[0]
```

Appears to fail with rxjs-es, rxjs or neither installed via npm. Does this library have some undocumented dependency? Does the build need to be configured to handled this shim?

**Comment by chriscareycode** [comment]
I have the exact same error when I try using this :(

**Comment by mike-north** [comment]
I'm not able to reproduce this. Can either of you create a simple project that demonstrates this problem?

**Comment by chriscareycode** [comment]
Hi Mike. I just tried:

`ember new ember-rx-shim-test`
`ember install ember-rx-shim`
`ember s`

and got the same error

`ember-cli: 2.7.0`
`node: 6.9.1`
`os: darwin x64`

**Comment by mike-north** [comment]
Ok, I can reproduce with ember-cli 2.7.0, and can confirm that it doesn't occur with 2.8.x or 2.9.x

Can you verify that this works for you with a more recent version of ember-cli?

**Comment by chriscareycode** [comment]
I do not see the error with 2.9.x. Thank you for creating this package. Very handy since RxJS does not have a Bower install

**Comment by mike-north** [comment]
Dug a little deeper and there seem to be some oddities with `treeForAddon` in this version of ember-cli. Fix and release incoming, which should have us working in ember-cli 2.7.0

**Comment by chriscareycode** [comment]
Thanks! Could you publish a 0.1.4 so I could pick up and test this patch? I'm getting 0.1.3 now which does not seem to have the fix.

**Comment by mike-north** [comment]
@chriscareycode done

**Comment by chriscareycode** [comment]
Thank you very much!! Works with Ember CLI 2.7.0 now!
